### ISSUE TITLE
Line truncation in *inspector* buffers

### ISSUE THREAD

**Issue by yantar92** [mmontone/emacs-inspector#20]
I am trying to use inspector to check a real nested list data and I find the current truncation behaviour inconvenient.
I just got the following

> proper list 
> ────────────────────────────────────────────────────────────────────────────────────────────
> length: 7
> 
> 0: paragraph
> 1: (:begin 1 :end 44 :contents-begin 1 :contents-end 42 :post-blank 2 :post-affili…
> 2: #("Text with newline " 0 18 (:parent (paragraph (:begin 1 :end 44 :contents-beg…
> 3: (line-break (:begin 19 :end 22 :post-blank 0 :parent (paragraph (:begin 1 :end …
> 4: #(" " 0 1 (:parent (paragraph (:begin 1 :end 44 :contents-begin 1 :contents-end…
> 5: (footnote-reference (:label "1" :type standard :begin 23 :end 31 :contents-begi…
> 6: #("more text.
> " 0 11 (:parent (paragraph (:begin 1 :end 44 :contents-begin 1 :co…

I see two problems with this text:
1. Upon resizing the window, the truncation does not get updated.
2. The truncation is much less convenient compared to what debugger
   does in similar scenarios - it would be more useful to truncate by depth:
   #("Text with newline " 0 18 (:parent (paragraph …)) )

**Comment by mmontone** [comment]
Ok. If you know how to code in elisp I welcome some tips on a possible implementation approach :)

**Comment by yantar92** [comment]
Check out `backtrace--print-to-string`.

**Comment by mmontone** [comment]
Thanks for the pointer. I'll look.

About the horizontal line, I couldn't find anything about how to draw a horizontal line that adapts to window size when it changes. It'd help if you can find something about that too.

**Comment by mmontone** [comment]
Or perhaps I should just consider removing the horizontal line and give emphasis to the title, with bold font, or color/background color, something like that.

**Comment by yantar92** [comment]
Try 

``` lisp
(with-silent-modifications (insert (propertize " " 'display '(space :align-to right-fringe))))
(with-silent-modifications (put-text-property (1- (point)) (point) 'face '(:strike-through t)))
```

**Comment by mmontone** [comment]
Ok. I'll do.

About the resizes, there's [window-size-change-functions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-Hooks.html#index-window_002dsize_002dchange_002dfunctions) hook.

I could try to hook and redraw the buffer when window changes. Truncation should be made to use current window size.

**Comment by mmontone** [comment]
Yes. I like the ability to be able to refresh the buffer in any case. That should be added.

**Comment by mmontone** [comment]
Pushed first attempt of truncation method based on backtrace--print-string. It looks better IMO. The ... buttons don't work though, because there's an inspector button that overwrites those and performs navigation to the object.

**Comment by yantar92** [comment]
> buttons don't work though, because there's an inspector button that overwrites those and performs navigation to the object.

Sounds like not a big deal. Navigation will reveal the details anyway. I will be able to tell more when I actually use this in practice.

**Comment by mmontone** [comment]
You can try it now with your data and give me some feedback. It is better IMO.

**Comment by mmontone** [comment]
I'm using this to test:

```
(require 'request)
(require 'json)

(request "https://www.govtrack.us/api/v2/role?current=true&role_type=senator"
  :success (lambda (&rest args)
	     (inspector-inspect (json-read-from-string (cl-getf args :data)))))
```

**Comment by yantar92** [comment]
Sure, it looksb better. But I was referring to actual daily usage when debugging staff, where I need to get meaningful understanding of the data. It will take time.

Should not prevent you from considering this aspect of the issue closed though. I will open a new issue if necessary.

**Comment by yantar92** [comment]
> Yes. I like the ability to be able to refresh the buffer in any case. That should be added.

A standard way would be `revert-buffer-function`.

**Comment by mmontone** [comment]
Ah. I've pushed an `inspector-refresh` command. I should look at the `revert-buffer-function`.

**Comment by mmontone** [comment]
I've hooked into `revert-buffer-function` in https://github.com/mmontone/emacs-inspector/commit/4d58a95ad9d8c6093d5daffd324aa9331fdb1430
