### ISSUE TITLE
[FR] Provide inspector command alternatives to `eval-expression` and `eval-last-sexp`

### ISSUE THREAD

**Issue by yantar92** [mmontone/emacs-inspector#22]
I have been playing with integrating inspector into my workflow and finally settled on alterning default `eval-expression` (M-:) and `eval-last-sexp` (C-x C-e).

What I have found is that I do not need inspector most of the time, but when I do, I do not want to bother alternative key bindings. Instead, I arranged C-u M-: to run `inspector-inspect-expression` and C-u C-x C-e to run `inspector-inspect-last-sexp`.

It could be useful to have wrapper commands that will do what I described: - with prefix argument, call inspector command and call the built-in command without prefix argument.

**Comment by mmontone** [comment]
I've removed those functions because they are not "pure" inspector stuff in my view. I instead added this as a recipe to the readme.
