### ISSUE TITLE
Autoloads!

### ISSUE THREAD

**Issue by Hugo-Heagren** [mmontone/emacs-inspector#3]
This package is awesome. But for the sake of easy use and onboarding, I think it would be good to autoload all of the entry-point commands. I'm not sure exactly which ones you would think are appropriate, but I would suggest, as a minimum, `inspect-object`, and all of the top-level interactive commands in the `;;------ Commands` section.

**Comment by mmontone** [comment]
I don't know how autoloads work. I'm just loading the inspector.el file into Emacs an using atm.

**Comment by mmontone** [comment]
I'll have a look and see if I understand how autoloads work.

**Comment by Hugo-Heagren** [comment]
> I don't know how autoloads work. I'm just loading the inspector.el file into Emacs an using atm.

Sorry, shouldn't have assumed. The best resource is the [elisp manual node on autoloads](https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html). As a very rough guide though, what you probably want to do is put a line like this:

```elisp
;;;###autload
```
above each command you want to be loaded automatically for the users. Have a look through the definitions of top-level user commands in some other packages on your machine to see examples.

**Comment by mmontone** [comment]
Ah. Cool stuff. I had seen autoloads declaration in files, but didn't know how they worked.

I think I can manage to add the autoloads myself, no need for PR.

Thanks for the suggestion and info!

**Comment by mmontone** [comment]
@Hugo-Heagren  

Like that?

Those are the top-level commands that should trigger loading in my opinion ..

**Comment by Hugo-Heagren** [comment]
LGTM!
