### ISSUE TITLE
This is doesn't compose with eros, let's do something about it

### ISSUE THREAD

**Issue by port19x** [mmontone/emacs-inspector#34]
Would it be possible to pivot your `emacs-inspector` and `emacs-tree-inspector` to be minor modes hooking into elisp evaluation and refreshing a buffer accordingly, similar to how `cider-inspect` operates?

That way `eros` can be focussed on visually enhancing the elisp experience while your inspector continues to give contextual information in a side-buffer.

I also find it jarring that `inspector-inspect-last-sexp` et. al switches focus to window containing the inspector buffer.

**Comment by mmontone** [comment]
> I also find it jarring that inspector-inspect-last-sexp et. al switches focus to window containing the inspector buffer.

You can now control that with `inspector-switch-to-buffer` variable. Good enough?

**Comment by port19x** [comment]
> I don't understand what this is about

Appologies, I was quite brief in my request.

The problem I have is that there is a minor mode I like for emacs lisp, called [eros](https://github.com/xiongtx/eros), that harmonizes with default evaluation commands.

`emacs-inspector`, at least as of right now, expects me to use `inspector-inspect-last-sexp` instead of `eval-last-sexp`.

I should have been more thorough in my own testing though. An oversight on my part is that `eros` makes it's own `eros-eval-last-sexp` available, so it doesn't compose any better or worse than `emacs-inspector`.

This makes using both your `emacs-inspector` and `eros` at the same time a bit of a challenge, but I'll leave it to you to suggest if and how we should proceed to that goal in this repo.

> You can now control that with inspector-switch-to-buffer variable. Good enough?

Yes, excellent. Give me a second to test it

**Comment by port19x** [comment]
It works, didn't work at first but that was due to weird caching of stuff. Resolved itself after an `eval-buffer`

**Comment by mmontone** [comment]
> emacs-inspector, at least as of right now, expects me to use inspector-inspect-last-sexp instead of eval-last-sexp

The thing is `inspector-inspect-last-sexp` does inspection, which is different from just evaluation with `eval-last-sexp`.

Perhaps you want some plugging similar to this?: https://github.com/mmontone/emacs-inspector#setup-evaluation-commands-using-prefix-arguments

You can probably implement your own command to plug Eros evaluation to the inspector somehow.

**Comment by port19x** [comment]
Yes, the following kind of works as a workaround, very similar to your readme excerpt:

```
(defun port19s-cider-envy (arg)
  "Like `eros-eval-last-sexp', but also inspect when called with prefix ARG."
  (interactive "P")
  (pcase arg
    ('(4) (inspector-inspect-last-sexp))
    (_ (call-interactively #'eros-eval-last-sexp))))
```

If I were to figure out how to plug eros to the inspector, would you be open to me contributing support for that?
This could work by checking if `eros-mode` is active and branching code accordingly

**Comment by mmontone** [comment]
> If I were to figure out how to plug eros to the inspector, would you be open to me contributing support for that?

Sorry, but probably not in the emacs-inspector code. I prefer having that as separate configuration.  At most maybe a mention with the code in the README, like what was done for evil-mode in the README.

**Comment by port19x** [comment]
That's fine. I'll see what I can do and perhaps it's easier to integrate inspector awareness into eros than the other direction anyway.

Thanks for adding the `inspector-switch-to-buffer` variable
