### ISSUE TITLE
Hide the [More] button when all entries of the list are shown initially

### ISSUE THREAD

**Issue by Gira-X** [mmontone/emacs-inspector#4]
As a quick demo to test this package, I ran `(inspect-expression '(list 1 2))` which showed this with the More button. Clicking the More button also does nothing apart from hiding it, so it should definitely be hidden initially.

![image](https://user-images.githubusercontent.com/15002298/164909384-a0d279d2-5c79-4573-b712-7d08da7dfb73.png)

**Comment by mmontone** [comment]
Yes, I'll try to correct that

**Comment by Gira-X** [comment]
Great, thank you for the quick fix :)
