### ISSUE TITLE
Fontification issue

### ISSUE THREAD

**Issue by joostkremers** [mmontone/emacs-inspector#5]
This looks like a package that could be very useful in certain situations. Thanks for working on this!

I noticed an issue with fontification in the inspector buffer: if a string is truncated, its fontification "leaks" into the next object:

![image](https://user-images.githubusercontent.com/191630/166837494-7d4ee4e6-c8f3-489c-8b95-387907db19ce.png)

**Comment by mmontone** [comment]
Thanks for reporting. I'll try to fix ..

**Comment by mmontone** [comment]
Mmm.. I think I've seen this bug before, but now I'm not able to reproduce ..

Do you have an snippet with elisp data that can use with the inspector to reproduce this bug?

**Comment by mmontone** [comment]
Ok. I'm able to reproduce if I inspect this: `(make-button 0 10)` and go deep with the inspector ..

**Comment by mmontone** [comment]
I've made inspector-mode inherit from fundamental-mode instead of emacs-lisp-mode, and that seems to fix the fontification issues.

How does it work for you?

**Comment by joostkremers** [comment]
> How does it work for you?

I must admit I have mixed feelings. It's better in the sense that the issue no longer occurs, but I did prefer the previous font effects. This is how it looks now:

![image](https://user-images.githubusercontent.com/191630/168168681-0219eb84-18f9-492b-b5ee-764388ded8cd.png)

Of course this depends on the theme I'm using, so I'd completely understand if you'd decide not to pursue it further.

**Comment by mmontone** [comment]
I think that theme fontifies in a specially ugly way.

This is how it looks around here:

![imagen](https://user-images.githubusercontent.com/436110/168173552-22d6cf63-422c-4d25-b66c-d3d89d5f15dc.png)

But I'll try to fontify using elisp faces and see what happens ...

**Comment by mmontone** [comment]
I've made another change. Using font-lock standard faces for some of the objects. How does it look for you now?

**Comment by joostkremers** [comment]
> I've made another change. Using font-lock standard faces for some of the objects. How does it look for you now?

It's much better now. :+1:
